# Recovered external research baseline from the last complete dashboard version.

POLICY_BASELINE = [('Hong Kong (SFC)',
  'Framework for Virtual Asset Trading Platforms (VATP) & Staking Circulars',
  'US-China tech-decoupling; HK positioning as primary non-western institutional liquidity hub.',
  'Maintains capital account inflows; offsets real estate stagnation by 0.4% GDP trajectory.',
  'Projected HK Web3 ecosystem revenue: $12.4B by 2028.',
  9,
  '2026-05-14'),
 ('European Union',
  'MiCA Phase 3 Enforcement (Stablecoin Asset-Referenced Token restrictions)',
  'EU strategic autonomy agenda pushing back against USD-pegged algorithmic hegemony.',
  'Imposes friction on retail cross-border capital velocity, slowing FinTech growth by 0.15% across Eurozone.',
  'Compliant enterprise infrastructure markets grow to €8.2B.',
  7,
  '2026-06-22'),
 ('United States',
  'Executive Order on Digital Asset Anti-Money Laundering Frameworks',
  'G7 sanctions coordination; weaponization of capital compliance metrics against illicit flows.',
  'Increased operational overhead for institutional staking; shifts venture deployment to offshore structures.',
  'US compliance-tech market expansions projected at $18.5B by 2029.',
  8,
  '2026-07-10'),
 ('Singapore (MAS)',
  'Tokenization Framework Implementation for Real World Assets (RWA)',
  "ASEAN economic integration competition; countering Hong Kong's aggressive stablecoin pipelines.",
  'Bolsters asset management index by an estimated $45B in AUM translation.',
  'RWA settlement system infrastructure revenues hit $5.1B.',
  8,
  '2026-07-25'),
 ('Brazil (BACEN)',
  'Law 14.478/2022 VASP Licensing + Drex CBDC Phase II Rollout',
  'Brazil asserting digital-currency leadership within Mercosur bloc; countering dollarization pressure.',
  'PIX + Drex integration projected to reduce payment-system costs by 0.3% of GDP annually.',
  'Brazilian fintech revenue to reach $23B by 2028; Drex DeFi rails open $4B B2B settlement market.',
  8,
  '2026-04-10'),
 ('Mexico (Banxico)',
  'Ley Fintech Implementation Decree: Crypto Exchange Regulatory Tightening',
  'Nearshoring boom driving demand for cross-border USD-MXN settlement efficiency; FATF grey-list risk.',
  'Restrictive Banxico stance limits crypto rails for remittances — $64B corridor remains fee-heavy.',
  'Compliant remittance-tech market: $1.8B revenue opportunity by 2027.',
  6,
  '2026-05-30'),
 ('Colombia (SFC)',
  'Regulatory Sandbox Phase III — Tokenized Sovereign Bonds Pilot',
  "Petro government's ambivalent crypto stance creates regulatory uncertainty; sandbox provides cover.",
  'Tokenized bond pilot could unlock $800M in retail investor access to sovereign debt instruments.',
  'Colombian fintech sector projected at $2.4B by 2027 if sandbox framework formalised.',
  7,
  '2026-06-15'),
 ('UAE (VARA / DIFC)',
  'VARA Institutional Custody & Staking Service Provider Licensing Round',
  'UAE positioning as bridge jurisdiction between East and West; countering EU MiCA compliance burden.',
  'Institutional crypto AUM in UAE projected to hit $25B by 2027; real estate tokenization adds $5B.',
  'VARA licensing ecosystem generating $2.1B in compliance and infrastructure services annually.',
  9,
  '2026-06-01'),
 ('Saudi Arabia (SAMA/CMA)',
  'CMA Digital Asset Trading Platform Consultation Paper',
  'Vision 2030 economic diversification drive; countering oil-revenue concentration risk.',
  'Regulated digital asset markets could contribute 0.2% to non-oil GDP by 2030.',
  'Saudi fintech sector: $3.5B revenue by 2029; RWA tokenization of Aramco assets under study.',
  7,
  '2026-07-01'),
 ('Bahrain (CBB)',
  'Crypto-Asset Module Amendment: DeFi Protocol Licensing Category',
  'Bahrain leveraging open regulatory posture to attract MENA fintech HQs from restrictive neighbours.',
  'DeFi licensing regime could attract $1.2B in protocol treasury relocations to Bahrain.',
  'CBB sandbox graduates generating $420M in annual financial-service revenues.',
  8,
  '2026-07-18'),
 ('Nigeria (SEC / CBN)',
  'SEC Nigeria Virtual Asset Service Provider Rules — Phase II Expansion',
  'CBN reversal allows banks to service licensed VASPs; signals pragmatic pivot after 2021 ban.',
  'Re-opening banking rails to crypto could channel $2B+ annual diaspora remittances via regulated platforms.',
  'Nigerian fintech market: $3.7B by 2028; licensed VASP sector projected at $600M.',
  8,
  '2026-05-20'),
 ('Kenya (CBK / CMA)',
  'Capital Markets Authority Draft Crypto-Asset Framework — Public Consultation',
  'East African fintech leadership at stake vs Rwanda and South Africa; IMF programme conditionality.',
  'Formalised crypto framework could grow domestic digital-asset market from $500M to $2B by 2028.',
  'Kenya fintech ecosystem — $1.1B revenues; DFS sector employing 40,000+.',
  7,
  '2026-06-10'),
 ('South Africa (FSCA)',
  'FSCA FSP Licensing Deadline for Crypto Asset Service Providers',
  'FATF greylisting (2023–2025) accelerating regulatory formalisation across financial services.',
  'FSCA licensing compliance driving $300M institutional custody infrastructure build-out.',
  'SA crypto market cap: $8B; regulated VASP sector to generate $900M by 2027.',
  7,
  '2026-07-05'),
 ('Rwanda (BNR)',
  'National Fintech & Innovation Policy 2022-2027 — Midterm Implementation Review',
  'Rwanda competing with Kenya and Mauritius as preferred East African financial hub for DFI capital.',
  'KIFC fintech licences attracting pan-African HQs; BNR sandbox graduates raising $180M in 2025.',
  'Rwanda fintech AUM: $2.4B by 2027; continental hub revenues at $350M.',
  8,
  '2026-07-22')]

FRIENDLINESS_BASELINE = [('UAE (VARA / DIFC)',
  'MENA',
  9,
  8,
  7,
  10,
  8,
  8.4,
  1.5,
  6.9,
  '⬆️ Exceptional',
  'Near-zero regulatory framework in 2016 (informal DIFC tolerance only). ADGM FinReg Sandbox launched 2016; VARA '
  'established 2022 with 7 comprehensive rulebooks. Free-zone 0% corporate tax, 0% CGT, 0% income tax make UAE the '
  'global benchmark for fiscal treatment. Emirates NBD, FAB, and Mashreq now formally serve licensed VASPs. '
  'Trajectory: from FATF grey-list risk to FATF compliant (2024) in under 4 years.',
  'VARA Rulebooks 2023–26; DIFC Innovation Testing Licence Guidelines; KPMG UAE FinTech Report 2025; IMF UAE Article '
  'IV Consultation 2025',
  2026),
 ('Singapore (MAS)',
  'APAC',
  9,
  9,
  7,
  8,
  8,
  8.2,
  3.5,
  4.7,
  '⬆️ Strong',
  "2016: informal 'do no harm' policy under MAS; no VASP licensing. Payment Services Act 2019 (amended 2023) created "
  "the world's most comprehensive PSP framework. MAS FinTech Regulatory Sandbox has <21-day response SLA — fastest "
  'institutional sandbox globally. 0% CGT; GST crypto exemption since 2020; 17% corporate tax with significant IP '
  'incentives. DBS, Standard Chartered, and OCBC actively serve licensed crypto and fintech firms.',
  'MAS Payment Services Act 2019/2023; CCAF Global Cryptoasset Benchmarking Study 2024; Singapore FinTech Association '
  'Annual Report 2025; Bloomberg Intelligence ASEAN FinTech 2025',
  2026),
 ('Hong Kong (SFC)',
  'APAC',
  8,
  7,
  5,
  9,
  6,
  7.0,
  2.8,
  4.2,
  '⬆️ Strong',
  '2016: SFC issued Statement on Regulatory Framework for VA Portfolios (conceptual only). VATP licensing framework '
  '(2023) and Stablecoin Ordinance (2025) provide institutional-grade clarity. 0% CGT, 0% VAT on digital assets; 16.5% '
  'corporate tax — strong fiscal stack. Banking access remains the key friction point: HSBC, Standard Chartered, and '
  'DBS HK serve only licensed operators; smaller VASPs still face debanking risk. VATP licensing process averages '
  '18–24 months and requires $5M+ in compliance spend.',
  'SFC VATP Circulars 2023–26; HK Stablecoin Ordinance 2025; KPMG HK FinTech Report 2025; HKMA CBDC Research 2024',
  2026),
 ('United Kingdom',
  'Europe',
  8,
  8,
  5,
  5,
  7,
  6.6,
  3.5,
  3.1,
  '⬆️ Moderate',
  '2016: FCA Innovation Hub launched; crypto informally tolerated but unregulated. FSMA 2023 brings digital assets '
  'into regulated perimeter. FCA crypto registration has historically rejected >75% of applicants — high bar but '
  'signals quality. FCA Innovation Hub and Digital Sandbox offer rapid pre-authorisation engagement (<3 months). CGT '
  '20–24% on crypto gains; no specific digital asset tax incentives. Barclays, HSBC, and Lloyds progressively opening '
  'to FCA-registered crypto firms post-2024.',
  'FCA Cryptoasset Register; FSMA 2023; HM Treasury Crypto Consultation 2023; FCA Innovation Hub Annual Report 2025; '
  'Bloomberg Intelligence UK FinTech 2025',
  2026),
 ('European Union (MiCA)',
  'Europe',
  9,
  5,
  5,
  5,
  7,
  6.2,
  3.0,
  3.2,
  '⬆️ Moderate',
  '2016: fragmented national regimes; Malta, Lithuania, Luxembourg as informal hubs. MiCA (fully applicable Dec 2024) '
  "is the world's most comprehensive crypto legislation — a single passport across 27 member states is strategically "
  'transformative. Tax varies dramatically: Germany 0% CGT after 1-year hold; France 30% flat; Portugal restored 28% '
  'CGT in 2023 after removing exemption. Average effective rate ~22%. DLT Pilot Regime sandbox exists but application '
  'timelines average 6–9 months.',
  'MiCA Regulation EU 2023/1114; ESMA CASP Guidelines 2024; CCAF EU Crypto Report 2024; LexisNexis European Digital '
  'Asset Law Review 2025',
  2026),
 ('LATAM (Brazil / Colombia)',
  'LATAM',
  7,
  7,
  6,
  5,
  6,
  6.2,
  2.0,
  4.2,
  '⬆️ Strong',
  '2016: no formal framework in any LATAM jurisdiction; crypto treated as commodity or currency ad hoc. Brazil Law '
  '14.478/2022 + BACEN VASP regulation (2023) are the regional anchor. Colombia SFC sandbox is among the most '
  'responsive in the Global South (<6 months entry). Tax treatment remains unfavourable: Brazil levies 15–22.5% CGT on '
  'crypto; Mexico requires full SAT reporting. PIX + Drex infrastructure significantly improves banking access for '
  'licensed operators. Nubank (100M+ users), BTG Pactual serve compliant crypto firms; traditional banks cautious.',
  'Brazil Law 14.478/2022; BACEN VASP Regulation 2023; Colombia SFC Sandbox Reports; Chainalysis LATAM Crypto Report '
  '2024; IMF LATAM Digital Finance 2024',
  2026),
 ('United States',
  'North America',
  5,
  4,
  3,
  4,
  6,
  4.4,
  4.2,
  0.2,
  '➡️ Stagnant',
  '2016: FinCEN guidance (2013) remains primary federal framework; states patchwork. Despite FIT21 passing the House '
  "(2024) and the Trump administration's pro-crypto pivot, no unified federal licensing regime exists as of 2026. "
  'SEC/CFTC jurisdictional ambiguity persists. Crypto taxed as property (IRS Rev. Rul. 2014-16): short-term gains at '
  'income rate up to 37%; long-term 15–20% CGT. No wash-sale rule exception until pending legislation. NYDFS '
  'BitLicense costs $500K–$2M to obtain. Custodia Bank approval (2025) is a positive signal but banking access remains '
  'the single biggest operational barrier for crypto firms.',
  'FIT21 Act (HR 4763); IRS Notice 2014-21; NYDFS BitLicense Regulations; Bloomberg Intelligence US Crypto Policy '
  '2025; LexisNexis US Digital Asset Law 2025',
  2026),
 ('Japan',
  'APAC',
  8,
  6,
  6,
  3,
  7,
  6.0,
  3.0,
  3.0,
  '⬆️ Moderate',
  '2016: Japan became first country to legally recognise Bitcoin (Payment Services Act amendment). Post-Coincheck hack '
  '(2018), FSA strengthened licensing requirements significantly. Japan leads on regulatory clarity and exchange '
  "licensing discipline; 30+ licensed exchanges. Critical weakness: crypto gains taxed as 'miscellaneous income' at "
  'marginal rates up to 55% — the highest effective crypto tax rate of any major jurisdiction globally. Japan FSA '
  'Regulatory Sandbox (2018) active but slower than Singapore. SBI, GMO, and Monex Group provide institutional banking '
  'infrastructure to licensed firms.',
  'Japan Payment Services Act (amended 2023); FSA Crypto Exchange Registration; CCAF Japan Crypto Report 2024; '
  'Bloomberg Intelligence Japan FinTech 2025',
  2026),
 ('South Korea',
  'APAC',
  7,
  6,
  5,
  5,
  6,
  5.8,
  2.5,
  3.3,
  '⬆️ Moderate',
  '2016: no formal framework; Financial Intelligence Unit (FIU) monitored exchanges informally. Virtual Asset User '
  'Protection Act (July 2024) introduced mandatory insurance, real-name account requirements, and on-chain monitoring '
  '— significant institutional leap. FSC licensing overhaul targeting institutional market by 2025 is partially '
  'implemented. Capital gains tax on crypto above 2.5M KRW annual threshold (20%) — moderate burden. Kakao Bank and KB '
  'Kookmin Bank serve licensed VASPs; others remain cautious.',
  'Virtual Asset User Protection Act 2024; FSC Digital Asset Policy 2025; CCAF Asia-Pacific Benchmarking 2024; '
  'LexisNexis Korea FinTech Law Review 2025',
  2026),
 ('Africa (Kenya / Nigeria / Rwanda)',
  'Africa',
  5,
  7,
  5,
  5,
  4,
  5.2,
  1.5,
  3.7,
  '⬆️ Moderate',
  '2016: zero formal crypto frameworks across Sub-Saharan Africa; CBN banned crypto in Nigeria (2021, reversed 2024). '
  'Kenya CBK Regulatory Sandbox (2021) is among the fastest-turnaround sandboxes in the Global South. Rwanda BNR '
  'Innovation Office and KIFC positioning Rwanda as continental fintech HQ. Nigeria SEC Digital Assets Rules (2022) + '
  'CBN 2024 reversal re-opens banking rails. Banking access remains the critical gap: most crypto firms report '
  "debanking; Kenya's M-Pesa rails provide a workaround for compliant fintechs. Nigeria proposed 10% levy on crypto "
  'gains; Kenya crypto tax framework under consultation.',
  'SEC Nigeria Digital Assets Rules 2022; CBN VASP Guidance 2024; CBK Sandbox Guidelines 2021; BNR Fintech Policy '
  '2022; Chainalysis Africa Crypto Report 2024; GSMA Mobile Money Report 2025',
  2026)]
